In [3]:
pip install simpful

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [4]:
import math
import numpy as np
import matplotlib.pyplot as plt
import sys, os
from simpful import *

# **Q1. Hopfield Network**

In [ ]:
class Hopfield:
  def __init__(self, N):
    self.N = N
    self.P = 0
    self.W = np.zeros((N, N), dtype=np.int32)
        
  def learning(self, P):
    for p in P:
      self.W += np.dot(np.vstack(p), np.vstack(p).T)
    np.fill_diagonal(self.W, 0.0)
    return self.W

  def predict(self, y, epochs):
    i = np.array(y)
    yhats_losses = [(i, math.inf)]
    stable = False
    for j in range(epochs):
      z = np.dot(i, self.W)
      y_hat = np.sign(z)
      equality = np.equal(y, y_hat)
      temp = np.count_nonzero(equality)
      loss = self.P - temp
      yhats_losses.append((y_hat, loss))
      stability = np.array_equal(yhats_losses[-1][0], yhats_losses[-2][0])
      if (stability):
        if j == 0:
          stable = True
        return y_hat, stable

    yp = min(result, key = lambda t: t[1])[0]
    return yp, stable

## Q1.a

In [ ]:
x1 =  np.array([-1, -1, 1, -1, 1, -1, -1, 1])
x2 = np.array([-1, -1, -1, -1, -1, 1, -1, -1])
x3 = np.array([-1, 1, 1, -1, -1, 1, -1, 1])
patterns = np.array([x1, x2, x3])
hopfield = Hopfield(8)
hopfield.learning(patterns)
for pattern in patterns:
  result, stability = hopfield.predict(pattern, epochs=10)
  print("pattern: ", pattern," ", "Result: ", result, " ", "Stability: ", stability)

pattern:  [-1 -1  1 -1  1 -1 -1  1]   Result:  [-1 -1  1 -1  1 -1 -1  1]   Stability:  True
pattern:  [-1 -1 -1 -1 -1  1 -1 -1]   Result:  [-1 -1 -1 -1 -1  1 -1 -1]   Stability:  True
pattern:  [-1  1  1 -1 -1  1 -1  1]   Result:  [-1  1  1 -1 -1  1 -1  1]   Stability:  True


## Q1.b

In [ ]:
x1n =  np.array([1, -1, 1, -1, 1, -1, -1, 1])
x2n = np.array( [1, 1, -1, -1, -1, 1, -1, -1])
x3n = np.array([1, 1, 1, -1, 1, 1, -1, 1])
patterns = np.array([x1n, x2n, x3n])
for pattern in patterns:
  result, stability = hopfield.predict(pattern, epochs=10)
  print("pattern: ", pattern," ", "Result: ", result, " ", "Stability: ", stability)

pattern:  [ 1 -1  1 -1  1 -1 -1  1]   Result:  [-1 -1  1 -1  1 -1 -1  1]   Stability:  False
pattern:  [ 1  1 -1 -1 -1  1 -1 -1]   Result:  [-1 -1 -1  1 -1  1  1 -1]   Stability:  False
pattern:  [ 1  1  1 -1  1  1 -1  1]   Result:  [-1  1  1 -1 -1 -1 -1  1]   Stability:  False


## Q1.c

In [ ]:
patterns = []
for i in range(256):
  x = bin(i)[2:].zfill(8)
  pattern = [2*int(x[i])-1 for i in range(8)]
  patterns.append(pattern)

count = 0
print("Stable patterns are: ")
for pattern in patterns:
  result, stability = hopfield.predict(pattern, epochs=10)
  if(stability):
    print(result)
    count += 1
print("The number of stable patterns is: ", count)

Stable patterns are: 
[-1 -1 -1 -1 -1  1 -1 -1]
[-1 -1  1 -1  1 -1 -1  1]
[-1  1  1 -1 -1  1 -1  1]
[ 1 -1 -1  1  1 -1  1 -1]
[ 1  1 -1  1 -1  1  1 -1]
[ 1  1  1  1  1 -1  1  1]
The number of stable patterns is:  6


#**Q3**

In [5]:
temperature = AutoTriangle(3, terms=['cool', 'norminal', 'warm'], universe_of_discourse=[0, 50])
humidity = AutoTriangle(5, terms=['very_low', 'low', 'normal', 'high', 'very_high'], universe_of_discourse=[0, 100])
rain_amount = AutoTriangle(5, terms=['very_low', 'low', 'normal', 'high', 'very_high'], universe_of_discourse=[0, 1000])
height = AutoTriangle(3, terms=['low', 'normal', 'high'], universe_of_discourse=[0, 1000])

In [6]:
FS = FuzzySystem()
FS.add_linguistic_variable("today_tmp", temperature)
FS.add_linguistic_variable("one_prev_day", temperature)
FS.add_linguistic_variable("two_prev_day", temperature)
FS.add_linguistic_variable("three_prev_day", temperature)
FS.add_linguistic_variable("humidity", humidity)
FS.add_linguistic_variable("rain_amount", rain_amount)
FS.add_linguistic_variable("height", height)

  ____  __  _  _  ____  ____  _  _  __   
 / ___)(  )( \/ )(  _ \(  __)/ )( \(  ) v2.9.0 
 \___ \ )( / \/ \ ) __/ ) _) ) \/ (/ (_/\ 
 (____/(__)\_)(_/(__)  (__)  \____/\____/

 Created by Marco S. Nobile (m.s.nobile@tue.nl)
 and Simone Spolaor (simone.spolaor@unimib.it)



In [7]:
Rules = ["IF (one_prev_day IS cool) AND (rain_amount IS high) THEN (today_tmp IS cool)",
        "IF (one_prev_day IS norminal) AND (rain_amount IS low) THEN (today_tmp IS norminal)",
        "IF (height IS high) AND (rain_amount IS high) THEN (today_tmp IS cool)",
        "IF (one_prev_day IS norminal) AND (two_prev_day IS cool) THEN (today_tmp IS norminal)",
        "IF (height IS low) AND (rain_amount IS very_low) THEN (today_tmp IS warm)",
        "IF (one_prev_day IS cool) OR (rain_amount IS high) THEN (today_tmp IS warm)",
        "IF (three_prev_day IS cool) OR (two_prev_day IS cool) THEN (today_tmp IS cool)",
        "IF (height IS normal)  OR (rain_amount IS very_low) THEN (today_tmp IS norminal)",
        "IF (three_prev_day IS cool) AND (two_prev_day IS warm) AND (one_prev_day IS warm) THEN (today_tmp IS warm)",
        "IF (rain_amount IS high) AND (humidity IS high) THEN (today_tmp IS cool)",
        "IF (humidity IS low) THEN (today_tmp IS warm)"]
FS.add_rules(Rules, verbose=True)

 * Regular expression is not matching with single atomic clause
 * Looking for an operator in (one_prev_day IS cool) AND (rain_amount IS high)
  -- Found (one_prev_day IS cool) *AND* (rain_amount IS high)
 * Simple clause with parentheses matched
 * Rule: c.(one_prev_day IS cool)
 * Simple clause with parentheses matched
 * Rule: c.(rain_amount IS high)
 * Added rule IF f.(c.(one_prev_day IS cool) AND c.(rain_amount IS high)) THEN ('today_tmp', 'cool')

 * Regular expression is not matching with single atomic clause
 * Looking for an operator in (one_prev_day IS norminal) AND (rain_amount IS low)
  -- Found (one_prev_day IS norminal) *AND* (rain_amount IS low)
 * Simple clause with parentheses matched
 * Rule: c.(one_prev_day IS norminal)
 * Simple clause with parentheses matched
 * Rule: c.(rain_amount IS low)
 * Added rule IF f.(c.(one_prev_day IS norminal) AND c.(rain_amount IS low)) THEN ('today_tmp', 'norminal')

 * Regular expression is not matching with single atomic clause
 * L

In [8]:
FS.set_variable("one_prev_day", 15)
FS.set_variable("two_prev_day", 10)
FS.set_variable("three_prev_day", 13)
FS.set_variable("humidity", 50)
FS.set_variable("rain_amount", 600)
FS.set_variable("height", 400)

In [9]:
result = FS.inference()
print(result)

{'today_tmp': 23.55766007779124}
